
spring:
  main:
    show-banner: false
  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      auto_quote_keyword: true
      ddl-auto: validate
      jdbc:
        time_zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:26556/integrity_hash
    username: ${INTEGRITY_HASH_DB_USER}
    password: ${INTEGRITY_HASH_DB_PASSWORD}
  application:
    name: FileIntegrityApp

server:
  port: 15400
  servlet:
          context-path: /api
  connection-timeout: 240000 # milliseconds (4 minute)
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.pkcs8.p12 ## We make as new one for production (Server Certificate)
    key-store-password: ${ssl_file_integrity_scanner} ## Ask me when doing PR and IÂ´ll send you the password from another channel
directory:
      endpoint-code: 4350345983458934 # It is possible to use an environment variable if required: ${ENDPOINT_CODE_1}
  