name: SCA Scan - File Integrity Scanner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
 
jobs:
  security-file-integrity_scanner:
    uses: pwssOrg/reusable-workflows/.github/workflows/sca_scan_base.yml@main
    with:
       working-path: File-Integrity-Scanner
       name-of-snyk-step: Check for vulnerabilities in File Integrity Scanner
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
