name: SCA Scan - File Integrity Scanner

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
 
jobs:
  security-file-integrity_scanner:
    uses: pwssOrg/reusable-workflows/.github/workflows/sca_scan_base_postgres.yml@4a6bd2983076c92d9e23c67cf7c18d327e99ec1d
    with:
       working-path: File-Integrity-Scanner
       name-of-snyk-step: Check for vulnerabilities in File Integrity Scanner
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      USER_FOR_SNYK: ${{ secrets.READ_PACKAGE_USER_FOR_WORKFLOWS }}
      READ_PACKAGE_TOKEN_INPUT: ${{ secrets.READ_PACKAGE_TOKEN_FOR_WORKFLOWS }}
